DATA:
  VAL_SPLIT: test
  DATALOADER_NAME: torch_timm_custom
  IMG_SIZE: (224,224) 
  BATCH_SIZE: 64
  VAL_BATCH_SIZE: 128
  INTERPOLATION: bilinear
MODEL: 
  NUM_CLASSES: 200
  NAME: swin_base_patch4_window7_224_in22k
  DROP_PATH_RATE: 0.1
  DROP_RATE: -1.
  LABEL_SMOOTHING: .1
TRAIN:
  EPOCHS: 50
  WARMUP_STEPS: 200
  WEIGHT_DECAY: 0.
  BASE_LR: 0.03
  WARMUP_LR: 1.0e-9
  MIN_LR: 1.0e-12
  OPTIMIZER:
    NAME: sgd
  CLIP_GRAD: 1.0
  LR_BS_SCALE: 64
AUG:
  NO_AUG: false
  SCALE: (0.7466666666,0.7466666666)  # 448/600
  RATIO: (1,1)

TEST:
  CROP: 0.7466666666  # 448/600 一定不能取更大，因为是向下取整
  BEST_MODEL_METRIC: ['main','acc1']

MODEL_EMA: true
LOG_WANDB: false
# TRAIN_MODE: train
EMA_DECAY: 0.9996