DATA:
  VAL_SPLIT: test
  TIMM: true
  IMG_SIZE: (224,224) #(384,384)
  BATCH_SIZE: 64
  VAL_BATCH_SIZE: 180
MODEL: 
  NUM_CLASSES: 200
  # swin_base_patch4_window12_384_in22k
  NAME: swin_small_patch4_window7_224
  DROP_PATH_RATE: .1
TRAIN:
  EPOCHS: 100
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 0.  # 0.00005
  BASE_LR: 0.0001
  WARMUP_LR: 1.0e-9
  MIN_LR: 1.0e-12
  OPTIMIZER:
    NAME: adamw
AUG:
  NO_AUG: false

TEST:
  CROP: 0.752
  BEST_MODEL_METRIC: ['main','acc1']
  
THUMB_MODE: true
MODEL_EMA: true
EMA_FORCE_CPU: false

LOG_WANDB: true
TRAIN_MODE: train
EMA_DECAY: 0.9998