DATA:
  VAL_SPLIT: test
  DATALOADER_NAME: torch_timm_custom
  IMG_SIZE: (448,448) #(384,384)
  BATCH_SIZE: 16
  VAL_BATCH_SIZE: 128
  INTERPOLATION: bilinear
MODEL: 
  NUM_CLASSES: 200
  # swin_base_patch4_window12_384_in22k
  NAME: vit_base_patch16_224_in21k
  DROP_PATH_RATE: .1
  LABEL_SMOOTHING: 0.1
TRAIN:
  EPOCHS: 50
  WARMUP_STEPS: 800
  # WARMUP_EPOCHS: 2
  WEIGHT_DECAY: 0.
  BASE_LR: 5.0e-4
  WARMUP_LR: 1.0e-9
  MIN_LR: 1.0e-12
  OPTIMIZER:
    NAME: adamw
  LR_BS_SCALE: 64
  ACCUMULATION_STEPS: 1
  # CLIP_GRAD: 5.0
AUG:
  NO_AUG: false
  SCALE: (0.7466666666,0.7466666666)  # 384 / 510
  RATIO: (1,1)

TEST:
  CROP: 0.7466666666
  BEST_MODEL_METRIC: ['main','acc1']

MODEL_EMA: false
LOG_WANDB: false
TRAIN_MODE: train
EMA_DECAY: 0.9996
SEED: 42