DATA:
  VAL_SPLIT: test
  DATALOADER_NAME: torch_timm_custom
  IMG_SIZE: (448,448) 
  BATCH_SIZE: 20
  VAL_BATCH_SIZE: 128
  INTERPOLATION: bilinear
MODEL: 
  NUM_CLASSES: 200
  NAME: vit_base_patch16_224_in21k
  DROP_PATH_RATE: 0.1
  DROP_RATE: -1.
  LABEL_SMOOTHING: 0.1
TRAIN:
  EPOCHS: 100
  WARMUP_STEPS: 1600
  WEIGHT_DECAY: 0.05
  BASE_LR: 5.0e-4
  WARMUP_LR: 1.0e-6  # https://github.com/rwightman/pytorch-image-models/issues/252
  MIN_LR: 1.0e-12
  OPTIMIZER:
    NAME: adam
  CLIP_GRAD: 1.0
  LR_BS_SCALE: 512

AUG:
  NO_AUG: false
  SCALE: (0.814545454545,0.814545454545)  # 448/550
  RATIO: (1,1)

TEST:
  CROP: 0.814545454545  # 448/550 一定不能取更大，因为是向下取整
  BEST_MODEL_METRIC: ['main','acc1']

MODEL_EMA: true
LOG_WANDB: false
# TRAIN_MODE: train
EMA_DECAY: 0.9996  # 根据 https://github.com/rwightman/pytorch-image-models/issues/252 imagenet b288, 0.99996得出 每epoch更新尺度尽量一致