DATA:
  IMG_SIZE: (448,448)
  DATALOADER_NAME: torch_fgvc_custom
  
MODEL: 
  NUM_CLASSES: 120
  # LABEL_SMOOTHING: 0.1
TRAIN:
  BASE_LR: 0.003
  LR_BS_SCALE: 16
  AS_LR_SCALE: false
  ACCUMULATION_STEPS: 1

AUG:
  TRANSFG_AA: false
  SCALE: (0.7466666666,0.7466666666)  # 448/600
TEST:
  CROP: 0.7466666666