CUDA_VISIBLE_DEVICES=0 python3 main.py --data-path=/home/tangwenhao/data/cqu_bpdd/ --output=/home/tangwenhao/output/ --title=swin_multi_view_persudo_clus --opts RDD_TRANS.INIT_STAGE_EPOCH 3 RDD_TRANS.CLUSTER.NAME kmeans RDD_TRANS.CLASSIFY_LOSS 1.0
CUDA_VISIBLE_DEVICES=0 python3 main.py --data-path=/home/tangwenhao/data/cqu_bpdd/ --output=/home/tangwenhao/output/ --title=swin_multi_view_persudo_clus --opts RDD_TRANS.INIT_STAGE_EPOCH 3 RDD_TRANS.CLUSTER.NAME kmeans RDD_TRANS.CLASSIFY_LOSS 10.0
CUDA_VISIBLE_DEVICES=0 python3 main.py --data-path=/home/tangwenhao/data/cqu_bpdd/ --output=/home/tangwenhao/output/ --title=swin_multi_view_persudo_clus --opts RDD_TRANS.INIT_STAGE_EPOCH 3 RDD_TRANS.CLUSTER.NAME kmeans RDD_TRANS.CLASSIFY_LOSS 0.1
CUDA_VISIBLE_DEVICES=0 python3 main.py --data-path=/home/tangwenhao/data/cqu_bpdd/ --output=/home/tangwenhao/output/ --title=swin_multi_view_persudo_clus --opts RDD_TRANS.INIT_STAGE_EPOCH 3 RDD_TRANS.CLUSTER.NAME kmeans RDD_TRANS.CLASSIFY_LOSS 1.0 RDD_TRANS.NOT_INST_TEST True
CUDA_VISIBLE_DEVICES=0 python3 main.py --data-path=/home/tangwenhao/data/cqu_bpdd/ --output=/home/tangwenhao/output/ --title=swin_multi_view_persudo_clus --opts RDD_TRANS.INIT_STAGE_EPOCH 3 RDD_TRANS.CLUSTER.NAME kmeans RDD_TRANS.CLASSIFY_LOSS 10.0 RDD_TRANS.NOT_INST_TEST True
CUDA_VISIBLE_DEVICES=0 python3 main.py --data-path=/home/tangwenhao/data/cqu_bpdd/ --output=/home/tangwenhao/output/ --title=swin_multi_view_persudo_clus --opts RDD_TRANS.INIT_STAGE_EPOCH 3 RDD_TRANS.CLUSTER.NAME kmeans RDD_TRANS.CLASSIFY_LOSS 0.1 RDD_TRANS.NOT_INST_TEST True
# 加上多视角
CUDA_VISIBLE_DEVICES=0 python3 main.py --data-path=/home/tangwenhao/data/cqu_bpdd/ --output=/home/tangwenhao/output/ --title=swin_multi_view_persudo_clus --opts RDD_TRANS.INIT_STAGE_EPOCH 3 RDD_TRANS.CLUSTER.NAME kmeans RDD_TRANS.CLASSIFY_LOSS 1.0 AUG.MULTI_VIEW waek_none
CUDA_VISIBLE_DEVICES=0 python3 main.py --data-path=/home/tangwenhao/data/cqu_bpdd/ --output=/home/tangwenhao/output/ --title=swin_multi_view_persudo_clus --opts RDD_TRANS.INIT_STAGE_EPOCH 3 RDD_TRANS.CLUSTER.NAME kmeans RDD_TRANS.CLASSIFY_LOSS 1.0 AUG.MULTI_VIEW strong_none
CUDA_VISIBLE_DEVICES=0 python3 main.py --data-path=/home/tangwenhao/data/cqu_bpdd/ --output=/home/tangwenhao/output/ --title=swin_multi_view_persudo_clus --opts RDD_TRANS.INIT_STAGE_EPOCH 3 RDD_TRANS.CLUSTER.NAME kmeans RDD_TRANS.CLASSIFY_LOSS 1.0 AUG.MULTI_VIEW strong_waek
# 两个类
CUDA_VISIBLE_DEVICES=0 python3 main.py --data-path=/home/tangwenhao/data/cqu_bpdd/ --output=/home/tangwenhao/output/ --title=swin_multi_view_persudo_clus --opts RDD_TRANS.INIT_STAGE_EPOCH 3 RDD_TRANS.CLUSTER.NAME kmeans RDD_TRANS.CLASSIFY_LOSS 1.0 RDD_TRANS.INST_NUM_CLASS 2 RDD_TRANS.NOT_INST_TEST True