CUDA_VISIBLE_DEVICES=0 python3 main.py --data-path=/home/tangwenhao/data/cqu_bpdd/ --output=/home/tangwenhao/output/ --title=swin_multi_view_persudo_noclus --opts RDD_TRANS.CLUSTER.NAME None
CUDA_VISIBLE_DEVICES=0 python3 main.py --data-path=/home/tangwenhao/data/cqu_bpdd/ --output=/home/tangwenhao/output/ --title=swin_multi_view_persudo_noclus --opts RDD_TRANS.CLUSTER.NAME None RDD_TRANS.TEST_THR 0.75
CUDA_VISIBLE_DEVICES=0 python3 main.py --data-path=/home/tangwenhao/data/cqu_bpdd/ --output=/home/tangwenhao/output/ --title=swin_multi_view_persudo_noclus --opts RDD_TRANS.CLUSTER.NAME None RDD_TRANS.TEST_THR 0.5
CUDA_VISIBLE_DEVICES=0 python3 main.py --data-path=/home/tangwenhao/data/cqu_bpdd/ --output=/home/tangwenhao/output/ --title=swin_multi_view_persudo_noclus --opts RDD_TRANS.CLUSTER.NAME None RDD_TRANS.TEST_THR 0.95
CUDA_VISIBLE_DEVICES=0 python3 main.py --data-path=/home/tangwenhao/data/cqu_bpdd/ --output=/home/tangwenhao/output/ --title=swin_multi_view_persudo_noclus --opts RDD_TRANS.CLUSTER.NAME None RDD_TRANS.THR_ABS_UPDATE_NAME sigmod 
CUDA_VISIBLE_DEVICES=0 python3 main.py --data-path=/home/tangwenhao/data/cqu_bpdd/ --output=/home/tangwenhao/output/ --title=swin_multi_view_persudo_noclus --opts RDD_TRANS.CLUSTER.NAME None AUG.MULTI_VIEW None
CUDA_VISIBLE_DEVICES=0 python3 main.py --data-path=/home/tangwenhao/data/cqu_bpdd/ --output=/home/tangwenhao/output/ --title=swin_multi_view_persudo_noclus --opts RDD_TRANS.CLUSTER.NAME None RDD_TRANS.FILTER_SAMPLES True
CUDA_VISIBLE_DEVICES=0 python3 main.py --data-path=/home/tangwenhao/data/cqu_bpdd/ --output=/home/tangwenhao/output/ --title=swin_multi_view_persudo_clus --opts RDD_TRANS.NOT_INST_TEST True
CUDA_VISIBLE_DEVICES=0 python3 main.py --data-path=/home/tangwenhao/data/cqu_bpdd/ --output=/home/tangwenhao/output/ --title=swin_multi_view_persudo_clus --opts RDD_TRANS.NOT_INST_TEST True RDD_TRANS.INST_NUM_CLASS 2
