DATA:
  TIMM: false
  IMG_SIZE: (300,300) #(384,384)
  BATCH_SIZE: 32
  VAL_BATCH_SIZE: 96
  DATASET: cqu_bpdd
MODEL: 
  NUM_CLASSES: 8      
  # swin_base_patch4_window12_384_in22k  pvt_medium pvt_v2_b3
  NAME: tf_efficientnet_b3
  DROP_PATH_RATE: .1
TRAIN:
  EPOCHS: 30
  WARMUP_EPOCHS: 2
  MIN_LR : 5.0e-6           # 这是swin的参数， 5e-6，5e-7。config文件里是cub的参数，swinpim那个文章给的
  WARMUP_LR: 5.0e-7
  BASE_LR: 8.0e-4 
AUG:
  MULTI_VIEW: None
  NO_AUG: false
TEST:
  CROP: 0.
  BEST_MODEL_METRIC: ['main','macro_f1']     
  
THUMB_MODE: true
MODEL_EMA: true
#LOG_WANDB: true
#BINARYTRAIN_MODE: true
TRAINER:
  NAME: none