MODEL: 
  NUM_CLASSES: 120
  DATALOADER_NAME: torch_timm_custom
  # LABEL_SMOOTHING: 0.1
TRAIN:
  BASE_LR: 0.003
  LR_BS_SCALE: 16.0
  AS_LR_SCALE: false
  ACCUMULATION_STEPS: 4
AUG:
  TRANSFG_AA: false

