DATA:
  VAL_SPLIT: test
  TIMM: true
  IMG_SIZE: (384,384)
  BATCH_SIZE: 8
MODEL: 
  NUM_CLASSES: 200
  NAME: swin_base_patch4_window12_384_in22k
TRAIN:
  EPOCHS: 50
  WEIGHT_DECAY: 0.0005
  BASE_LR: 0.0005
THUMB_MODE: true
