DATA:
  VAL_SPLIT: test
  TIMM: false
  IMG_SIZE: (384,384)
  BATCH_SIZE: 8
  VAL_BATCH_SIZE: 24
  NOR_CLS_INDEX: -1
MODEL: 
  NUM_CLASSES: 200
  NAME: rdd_trans_swin_base_patch4_window12_384_in22k
  DROP_PATH_RATE: .3
TRAIN:
  EPOCHS: 50
  WARMUP_EPOCHS: 1
  WEIGHT_DECAY: 0.0005
  BASE_LR: 0.0005
  WARMUP_LR: 1e-9
  MIN_LR: 1e-12
  OPTIMIZER:
    NAME: SGD
AUG:
  NO_AUG: false
  TIMM_TRANS: true
  MULTI_VIEW: strong_none
TEST:
  CROP: 0.752
  BEST_METRIC: top1
THUMB_MODE: false

RDD_TRANS:
  CLUSTER:
    NAME: gcn
    NUM_CLUSTER: 2
    IPS_ACTIVE_CONNECTION: 4
    IPS_K_AT_HOP: [ 10, 3 ]
    THR: 0.5
  PERSUDO_LEARNING: true
  PERSUDO_LABEL: false
  EMA_FORCE_CPU: false