RDD_TRANS:
  CLUSTER:
    CLUSTER_DISTANCE: cosine
    INIT: k-means++
    IPS_ACTIVE_CONNECTION: 2
    IPS_K_AT_HOP: [ 2, 0 ]
    NAME: spectral
    NUM_CLUSTER: 5
    NUM_INIT: 10
    N_COMPOENTS: None
    RBF_DISTANCE: euclidean
    RBF_GAMMA: 0.05
    SELECT_THR: 0.9 
    SPECTRAL_AFFINITY: rbf
    THR: 0.75
  EMA_DECAY: 0.9997
  EMA_DECAY_SCHEDULER: null
  EMA_DECAY_SCHEDULER_FLAT_RATIO: 0.01
  EMA_FORCE_CPU: false
  INIT_STAGE_EPOCH: 0
  INST_NUM_CLASS: 2
  NOR_THR: 0.05
  NOT_INST_TEST: true
  PERSUDO_LEARNING: false
  TEACHER_LOSS : null
  TEST_THR: 0.995