TEST:
  BEST_MODEL_METRIC: ['main','auc']
  CROP: 0.

DATA:
  DATALOADER_NAME: torch_img_multiviewpict
  IMG_SIZE: [224,224]
  
TRAINER:
  NAME: pict
  
MODEL:
  NAME: pict
  BACKBONE: swin_pict_small_patch4_window7_224
  NUM_CLASSES: 2
  DROP_PATH_RATE: .3
  TOGPU_MODEL_NAME: ['main','teacher']
  
DATA:
  NOR_CLS_INDEX: 0  # 在类别中，正常图片的类别索引，用于PicT算法，该值判断在DATA_NOR_INDEX之后

THUMB_MODE: false
BINARYTRAIN_MODE: true
  
PICT:
  CLUSTER:
    CLUSTER_DISTANCE: cosine
    PERSISTENT_CENTER: true
    NAME: None
    NUM_CLUSTER: 2
    SELECT_THR: 0.99  #0.99 在绝对阈值0.99时表现最好

  MULTI_VIEW: strong_none
  CLASSIFY_LOSS: 0.
  EMA_DECAY: 0.9998
  INST_NUM_CLASS: 2
  INST_TEST: true
  BAG_TEST: false
  TEST_THR: 0.8       # 0.9比0.95,0.99在绝对阈值0.99时表现逗号
  FILTER_SAMPLES: true
  # update it per iter
  THR_REL_EMA_DECAY: 0.99
  # 取最小的百分之几比例来更新，相对阈值是一种保证前提，保证一个包里面最少都要有这么多病害实例
  THR_REL_UPDATE_RATIO: 0.001
  # for update
  THR_ABS_DIS_LOW: 0.5
  THR_ABS_DIS_HIGH: 0.9

  THR_ABS_NOR_LOW: 0.9
  THR_ABS_NOR_HIGH: 0.95  # 0.99没有0.95好

  THR_FIL_NOR_LOW: 0.7
  THR_FIL_NOR_HIGH: 0.95

  THR_FIL_DIS: 0.

  THR_ABS_DIS_: false
  THR_ABS_NOR_: true
  THR_REL_: true
