DATA:
  VAL_SPLIT: test
  DATALOADER_NAME: torch_timm_pim
  IMG_SIZE: (384,384) #(384,384)
  BATCH_SIZE: 24
  VAL_BATCH_SIZE: 128
  INTERPOLATION: bilinear
MODEL: 
  NUM_CLASSES: 555
  # swin_base_patch4_window12_384_in22k
  NAME: swin_base_patch4_window12_384_in22k
  DROP_PATH_RATE: .2
TRAIN:
  EPOCHS: 50
  WARMUP_STEPS: 800
  # WARMUP_EPOCHS: 2
  WEIGHT_DECAY: 0.0005
  BASE_LR: 0.0005
  WARMUP_LR: 1.0e-9
  MIN_LR: 1.0e-12
  OPTIMIZER:
    NAME: sgd
  LR_BS_SCALE: 24
  ACCUMULATION_STEPS: 1
AUG:
  NO_AUG: false
  SCALE: (0.7529411764705,0.7529411764705)  # 384 / 510
  RATIO: (1,1)

TEST:
  CROP: 0.7529411764705
  BEST_MODEL_METRIC: ['main','acc1']

MODEL_EMA: true
LOG_WANDB: false
TRAIN_MODE: train
EMA_DECAY: 0.9996
SEED: 42