MODEL: 
  NUM_CLASSES: 100
  LABEL_SMOOTHING: 0.1
DATA:
  VAL_SPLIT: test
  DATALOADER_NAME: torch_timm_custom
# AUG:
#   TRANSFG_AA: true
TRAIN:
  EPOCHS: 100
  WARMUP_STEPS: 1600
  # WARMUP_EPOCHS: 2
  WEIGHT_DECAY: 0.0005
  CLIP_GRAD: 5.0
  OPTIMIZER:
    NAME: adamw
  
TRAIN_MODE: train
EMPTY_CACHE: true

