MODEL: 
  NUM_CLASSES: 100
  LABEL_SMOOTHING: 0.
  
DATA:
  DATALOADER_NAME: torch_timm_custom
  VAL_SPLIT: test
# AUG:
#   TRANSFG_AA: true
TRAIN:
  EPOCHS: 100
  WARMUP_STEPS: 1600
  WEIGHT_DECAY: 5.0e-4
  BASE_LR: 5.0e-4
  WARMUP_LR: 1.0e-9
  MIN_LR: 1.0e-12
  OPTIMIZER:
    NAME: sgd
  CLIP_GRAD: 0.
  LR_BS_SCALE: 16

AUG:
  SCALE: (0.814545454545,0.814545454545)

TEST:
  CROP: 0.814545454545

TRAIN_MODE: train

EMPTY_CACHE: true

